Feature/53908 lista de leads
FJala-Tr2020/back-end-e2 pull request #3
Opened 2021-07-09 03:22 UTC by soyhernan7

2021-07-09 13:20 UTC, eencinasq requested changes

2021-07-09 13:20 UTC, eencinasq commented on src/tests/version.spec.ts
> +it('Gets the version endpoint', async (done) => {
A good practice to write unit tests is to define first a set of test cases, which means we need to use **describe** as **test suite** and then inside of 'describe' add **test cases**
e.g
`
describe('<TEST SUITE NAME (IT CAN BE CLASS OR COMPONENT)>', () => {

  it('<TEST CASE NAME>', () => {
    // WRITE TEST
  })
}
`

2021-07-09 13:20 UTC, eencinasq commented on src/tests/leads.spec.ts
> +it('Gets the leads', async (done) => {
A good practice to write unit tests is to define first a set of test cases, which means we need to use describe as test suite and then inside of 'describe' add test cases
e.g
`
describe('<TEST SUITE NAME (IT CAN BE CLASS OR COMPONENT)>', () => {

it('', () => {
// WRITE TEST
})
}
`

2021-07-09 13:23 UTC, eencinasq commented
Unit Test is failing:
![image](https://user-images.githubusercontent.com/6945588/125084092-21ff6000-e097-11eb-8efd-b13656fc6bed.png)

make sure all tests should be pass successfully, please.

2021-07-16 22:22 UTC, Carlos-YD requested changes
@soyhernan7 Please update the tests according to Edwin's feedback

2021-07-21 16:40 UTC, Carlos-YD requested changes
Still waiting for changes based on Edwin's comments

2021-07-27 00:34 UTC, marcelo-yourday commented
This pull request is not valid anymore.

2021-07-27 00:34 UTC, closed without merging

2021-07-27 00:34 UTC, marcelo-yourday commented
This code was already merged in other PR.