add send mail on new lead
FJala-Tr2020/back-end-e2 pull request #7
Opened 2021-07-22 11:27 UTC by CGary

2021-07-23 03:42 UTC, Carlos-YD requested changes

2021-07-23 03:42 UTC, Carlos-YD commented on .eslintrc
> +        "prettier/prettier": 0
Why are we overriding _prettier_ configurations?

2021-07-23 03:42 UTC, Carlos-YD commented on src/server.ts
> +
Would be nice to just configure the app in this file and move the routes to another file(s), in the future for every new endpoint we will have to add more and more code here. Please check how to use **routers** in expressJS.

2021-07-28 02:30 UTC, CGary commented on .eslintrc
> +        "prettier/prettier": 0
I removed the line of code

2021-07-28 02:32 UTC, CGary commented on src/server.ts
> +
I added files with the routes of each endpoint

2021-08-02 09:19 UTC, marcelo-yourday approved these changes

2021-08-02 19:44 UTC, kleyla approved these changes

2021-08-02 20:23 UTC, merged